[package]
name = "apm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.78"
gdk = { version = "0.7.3", package = "gdk4", features = ["v4_12"] }
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
gtk-layer-shell = { version = "0.2.0", package = "gtk4-layer-shell" }
