spacing = 25

[[buttons]]
label = "Poweroff"
icon = "~/coding/acw/examples/shutdown.png"
cmd = "systemctl poweroff"
keybind = "p"
padding = 50
icon_size = 25

[[buttons]]
label = "Reboot"
icon = "examples/shutdown.png"
cmd = "systemctl reboot"
keybind = "r"
padding_x = 40
padding_y = 50
icon_width = 25

[[buttons]]
label = "Lock"
icon = "examples/shutdown.png"
cmd = "wezterm"
keybind = "l"
padding_left = 50
padding_right = 40
padding_top = 30
padding_bottom = 20
icon_height = 25
