[[buttons]]
label = "Poweroff"
icon = "examples/shutdown.png"
cmd = "systemctl poweroff"
keybind = "p"

[[buttons]]
label = "Reboot"
icon = "examples/shutdown.png"
cmd = "systemctl reboot"
keybind = "r"

[[buttons]]
label = "Lock"
icon = "examples/shutdown.png"
cmd = "echo 'Implement locking'"
keybind = "l"
