spacing = 50

[[buttons]]
icon = "icons/poweroff.png"
label = "Power Off"

[[buttons]]
icon = "icons/reboot.png"
label = "Reboot"

[[buttons]]
icon = "icons/lock.png"
label = "Lock"

[[buttons]]
icon = "icons/sleep.png"
label = "Sleep"

[[buttons]]
icon = "icons/logout.png"
label = "Logout"
