spacing = 50

[[buttons]]
icon = "icons/poweroff.png"
label = "Power Off"
key = "p"
cmd = "systemctl poweroff"

[[buttons]]
icon = "icons/reboot.png"
label = "Reboot"
key = "r"
cmd = "systemctl reboot"

[[buttons]]
icon = "icons/lock.png"
label = "Lock"
key = "l"

[[buttons]]
icon = "icons/sleep.png"
label = "Sleep"
key = "s"
cmd = "systemctl suspend"

[[buttons]]
icon = "icons/logout.png"
label = "Logout"
key = "q"
cmd = "loginctl terminate-user $USER"
