name: Build

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true

  #     - uses: Swatinem/rust-cache@v2
  #       name: Cache dependencies

  #     - name: Install build deps
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install build-essential libgtk-4-dev libgtk-layer-shell-dev

  #     - name: Build
  #       run: cargo build --verbose

  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: arunim
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build --print-build-logs
